package com.cg.postpo;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class WorkOrderDetails implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String woNumber;
	private java.lang.String poNumber;
	private java.lang.String sysWOId;

	private java.lang.String subSysWOId;
	private java.lang.String division;
	public WorkOrderDetails() {
	}

	public java.lang.String getWoNumber() {
		return this.woNumber;
	}

	public void setWoNumber(java.lang.String woNumber) {
		this.woNumber = woNumber;
	}

	public java.lang.String getPoNumber() {
		return this.poNumber;
	}

	public void setPoNumber(java.lang.String poNumber) {
		this.poNumber = poNumber;
	}

	public java.lang.String getSysWOId() {
		return this.sysWOId;
	}

	public void setSysWOId(java.lang.String sysWOId) {
		this.sysWOId = sysWOId;
	}

	public java.lang.String getSubSysWOId() {
		return this.subSysWOId;
	}

	public void setSubSysWOId(java.lang.String subSysWOId) {
		this.subSysWOId = subSysWOId;
	}

	public java.lang.String getDivision() {
		return this.division;
	}

	public void setDivision(java.lang.String division) {
		this.division = division;
	}

	public WorkOrderDetails(java.lang.String woNumber,
			java.lang.String poNumber, java.lang.String sysWOId,
			java.lang.String subSysWOId, java.lang.String division) {
		this.woNumber = woNumber;
		this.poNumber = poNumber;
		this.sysWOId = sysWOId;
		this.subSysWOId = subSysWOId;
		this.division = division;
	}

}